[project]
site_name = "bizdate"
nav = [
    { "Home" = "index.md" },
    { "API Reference" = [
        { BusinessCalendar = "reference/buscal.md" },
        { BusdayConvention = "reference/busday_conv.md" },
    ] },
]

[project.theme]
font.code = "FiraCode"
features = ["navigation.path"]

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "green"
accent = "green"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "green"
accent = "green"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["python/bizdate"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
find_stubs_package = true
